<input
        type="text"

        <?php $this->attr('name', '') ?>
        <?php $this->attrIf('value', '') ?>

        <?php $this->attrIf('class') ?>
        <?php $this->attrIf('id') ?>

        <?php $this->attrIf('autocomplete') ?>
        <?php $this->attrIf('disabled') ?>
        <?php $this->attrIf('placeholder') ?>
        <?php $this->attrIf('spellcheck') ?>

        <?php $this->attrIf('tabindex') ?>
\>
